spring.application.name=currency-converter
server.port=8081

# logger config
logging.pattern.console = %d{dd-mm-yyyy hh-MM-ss} [%level] %c{1} --> %m%n

# free currency converter
currency.convert.base.url=https://api.freecurrencyapi.com/v1/latest
currency.convert.apikey=fca_live_fCLcNr2kHUisw1gkrEyrMgLfwHbIqTNULHIPT2by