#server.port=8081
#
#spring.application.name=module2
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:D:/Coding Shuttle/Module2-SpringbootMVCandRestfulAPIs
#spring.datasource.username=anujDB
#spring.datasource.password=Anuj123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true