server:
  port: 8081

jwt:
  secretKey: sdnvnfdreognovnfvkmrp23-05930vdjvn5903fnvfdnvjnbr2r3

spring:
  application:
    name: SpringDataJPA
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_mgmt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
#    sql:
#      init:
#        mode: always

  security:
    user:
      name: atharva
      password: pass

logging:
  level:
    org:
      springframework:
        security: DEBUG